### ISSUE TITLE
frigate hass card - error

### ISSUE THREAD

**Issue by hack2spider** [dermotduffy/frigate-hass-card#1156]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 735, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 775, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/usr/src/homeassistant/homeassistant/components/ring/camera.py", line 145, in handle_async_mjpeg_stream
    await stream.close()
  File "/usr/local/lib/python3.10/site-packages/haffmpeg/core.py", line 159, in close
    await self._loop.run_in_executor(None, _close)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/haffmpeg/core.py", line 154, in _close
    self._proc.stdin.write(b"q")
BrokenPipeError: [Errno 32] Broken pipe

023-05-11 23:09:51.236 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.240 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.241 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.242 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.244 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.246 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.248 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.249 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.250 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.251 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.253 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.254 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long
2023-05-11 23:09:51.255 ERROR (MainThread) [frontend.js.latest.202305033] http://10.0.0.4:8123/hacsfiles/frigate-hass-card/live-go2rtc-c50a1f44.js:1:4855 RangeError: source array is too long

**Comment by hack2spider** [comment]
it was a ring camera in one of the cards causing problems.

**Comment by dermotduffy** [comment]
Can you clarify what you're seeing and what the problem is? The issue template helps guide you to provide the information necessary to debug/support. As is, I can't tell what the problem is, or if there is even a problem or how to reproduce it.

**Comment by dermotduffy** [comment]
Please re-open if the issue continues, providing the information requested in the issue template. Thanks!
