### ISSUE TITLE
Issue with the Frigate 0.10 beta

### ISSUE THREAD

**Issue by MrAnonymous722** [dermotduffy/frigate-hass-card#203]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**V2.0.0

**Last working release (if known):**V2.0.0

**Browser and Operating System:**Google Chrome, Windows 10. Also shows up on Google Chrome on my iPhone.

**Description of problem:**When an 'in progress' event is occurring, the card breaks for the duration of that event. 
![image](https://user-images.githubusercontent.com/26932670/142731616-0dc1f0d6-9f54-4bd4-b167-531f9e5187de.png)

**Javascript errors shown in the web inspector (if applicable):**None that I can see.

**Additional information:**Not sure if this is even a valid bug, since its a beta release of Frigate, but I hadn't seen it in the open bugs here so I decided to let y'all know.

**Comment by dermotduffy** [comment]
Thanks for the report. Can you include the card configuration and some steps for me to reproduce the error?

**Comment by blakeblackshear** [comment]
A few things to note. When there is an "In progress" event, the end_time for the event is null. Also, the endpoint for getting the snapshot needs to be `/api/events/<event_id>/snapshot.jpg`. This should work for both in progress and complete events, so I am switching the UI to use this endpoint everywhere.

**Comment by dermotduffy** [comment]
@blakeblackshear The card never directly communicates with frigate, and relies only on the integration (incl. its views) to do so. It won't have access to end_time (or the raw event object at all). For event viewing, it will use whatever endpoint the `media_source` in the Frigate integration code returns, which is currently `/api/frigate/<clientid>/clips/<camera>-<eventid>.jpg`, which gets proxied to `/clips/<camera>-<eventid>.jpg`.

Given the above direction, I think you're probably suggesting we move the integration to proxying to `/api/events/<eventid>/snapshot.jpg` instead (which would mean the card does likewise). 

Let me know if I'm not following what you're getting at (I haven't yet tried to reproduce what @MrAnonymous722 has described).

**Comment by blakeblackshear** [comment]
That's exactly right. Snapshots should then work for in progress events too. It's possible that the events endpoint has a bug when there is an in progress event too. I can do some testing on that.

**Comment by blakeblackshear** [comment]
Got this browsing around with an in progress event:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 99, in websocket_browse_media
    media = await async_browse_media(hass, msg.get("media_content_id"))
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 78, in async_browse_media
    return await _get_media_item(hass, media_content_id).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 79, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/frigate/media_source.py", line 652, in async_browse_media
    return self._browse_events(
  File "/config/custom_components/frigate/media_source.py", line 724, in _browse_events
    event_items = self._build_event_response(identifier, events)
  File "/config/custom_components/frigate/media_source.py", line 795, in _build_event_response
    title=f"{dt.datetime.fromtimestamp(event['start_time'], DEFAULT_TIME_ZONE).strftime(DATE_STR_FORMAT)} [{int(event['end_time']-event['start_time'])}s, {event['label'].capitalize()} {int(event['top_score']*100)}%]",
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by MrAnonymous722** [comment]
As far as reproduction goes, upgrade to the a beta release of 0.10 and while an event is in progress, load a lovelace view with the card on it. It should error out similarly to my screenshot. Then refresh the view after the event is no longer "in progress" and it should return to normal.

**Comment by dermotduffy** [comment]
@MrAnonymous722 Can you provide your card configuration? [Otherwise I won't know what view the card is trying to load]

**Comment by MrAnonymous722** [comment]
Ah right, sorry about that.

```
type: custom:frigate-card
camera_entity: camera.driveway_cam
motion_entity: binary_sensor.driveway_cam_person_motion
frigate:
  url: http://192.168.0.3:5000
  camera_name: driveway-cam
view:
  default: snapshots
live:
  provider: frigate
  webrtc:
    entity: camera.driveway_cam_2
event_viewer:
  autoplay_clip: true
menu:
  mode: above
```

**Comment by dermotduffy** [comment]
Thank you both. I'll take a look.
