### ISSUE TITLE
Thumbnails taking much longer to load

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#941]
Hi, I just rebuilt release-4.1.0 from source and I noticed this issue.

The thumbnails takes much longer to load in the media viewer, and I notice this error popping up in console logs which seems to be related:

```
card-0c55e731.js:75 Error: Failed to receive response from Home Assistant for request
    at Pp (card-0c55e731.js:141:10229)
    at async QM (card-0c55e731.js:320:22494)
    at async i (card-0c55e731.js:320:39222)
    at async Promise.all (/lovelace/index 0)
    at async pT.getEvents (card-0c55e731.js:320:39410)
    at async a (card-0c55e731.js:320:16313)
    at async Promise.all (/lovelace/index 0)
    at async o (card-0c55e731.js:320:16637)
    at async Promise.all (/lovelace/index 0)
    at async MM._handleQuery (card-0c55e731.js:320:16719) {request: {…}, response: {…}}
```

PS: I'm using Frigate 0.12.

**Comment by dermotduffy** [comment]
Thanks for testing from v4.1.0 branch. There are substantial changes to the codebase even though it probably mostly looks the same, so there will definitely be bugs to squish here.

That seems to suggest the integration didn't properly respond to the request. You should be able to click the `...` for the request and response to see what they were? (Just to make sure it was thumbnail related). Anything in your HA logs?

**Comment by dermotduffy** [comment]
BTW: Since you're building yourself, if you set `DEV=1` in your environment, you'll get source mapped output that will make that stacktrace more useful.

**Comment by felipecrs** [comment]
Hm... cool. I will check for what more information I have.

I noticed that I unintentionally had disabled snapshots for one of my cameras in Frigate UI, so I don't know, maybe that's why.

I'll keep you posted.

BTW, would you prefer that I don't report issues for the release-4.1.0 branch?

**Comment by dermotduffy** [comment]
> BTW, would you prefer that I don't report issues for the release-4.1.0 branch?

The opposite: would really appreciate bug reports for anything in 4.1.0 that seems broken, especially if it behaves differently than it used to.

**Comment by felipecrs** [comment]
@dermotduffy this shows up in my HA logs:

```
beta:5000/api/portao/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.289 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/video_porteiro/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.292 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/rua/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.295 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/morro/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.298 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/portao/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.301 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/events/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.305 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/video_porteiro/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.308 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/rua/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.310 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/morro/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.314 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/portao/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.317 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/video_porteiro/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.321 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/rua/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.324 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/morro/recordings/summary?timezone=America/Sao_Paulo:
2023-02-17 18:35:37.327 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/portao/recordings/summary?timezone=America/Sao_Paulo:
```

**Comment by felipecrs** [comment]
I'm running:

https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v4.0.0-beta4
https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0-beta8

**Comment by dermotduffy** [comment]
Just a one off, or continually? If the former, is it possible Frigate was restarting at the time?

**Comment by felipecrs** [comment]
It happens every time I try to open the Media Gallery of the card. It takes a lot of time to load the thumbnails, and I suppose that's the reason.

Also, this is not some times... Happens every time. Maybe Frigate and its APIs aren't working well.

I will check tomorrow if the same request works when calling Frigate directly, to see if the integration may be the culprit.

**Comment by felipecrs** [comment]
The same request works normally if I call it from the SSH add-on.

Well, apparently my integration is not talking to the Frigate add-on correctly. That must be why the problem.

I think everything which uses MQTT is working like detected objects and so, but everything that has to do with the API doesn't work.

Example:

```
2023-02-18 14:06:39.104 ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-beta:5000/api/stats:
```

But:

```
$ curl -fssL http://ccab4aaf-frigate-beta:5000/api/stats
<works>
```

**Comment by felipecrs** [comment]
Ok, as this is clearly not a problem with the card but instead with the integration, I'll reopen this issue there.

**Comment by felipecrs** [comment]
Ok. Actually this has nothing to do with the new code in the branch or the integration. It's because I have multiple of the same cameras in the same card:

```yaml
cameras:
  - camera_entity: camera.video_porteiro
    live_provider: webrtc-card
    webrtc_card:
      url: video_porteiro
  - camera_entity: camera.rua
    live_provider: webrtc-card
    webrtc_card:
      url: rua
  - camera_entity: camera.morro
    live_provider: webrtc-card
    webrtc_card:
      url: morro
  - camera_entity: camera.portao
    live_provider: webrtc-card
    webrtc_card:
      url: portao
  - camera_entity: camera.video_porteiro
    live_provider: webrtc-card
    title: Vídeo Porteiro (HD)
    id: video_porteiro_hd
    webrtc_card:
      url: video_porteiro_hd
  - camera_entity: camera.rua
    live_provider: webrtc-card
    title: Rua (HD)
    id: rua_hd
    webrtc_card:
      url: rua_hd
  - camera_entity: camera.morro
    live_provider: webrtc-card
    title: Morro (HD)
    id: morro_hd
    webrtc_card:
      url: morro_hd
  - camera_entity: camera.portao
    live_provider: webrtc-card
    title: Portão (HD)
    id: portao_hd
    webrtc_card:
      url: portao_hd
```

Maybe the card tries to call the Frigate API twice for such cameras when I open the media gallery.

**Comment by dermotduffy** [comment]
> Maybe the card tries to call the Frigate API twice for such cameras when I open the media gallery.

Yeah, it definitely will. I'm not sure that's particularly incorrect though, i.e. as far as the card is concerned they _are_ different cameras. This still shouldn't result in the calls to the backend failing...

Let me investigate and see if there are incorrect duplicate calls happening here. But if it's just making 1 call per configured camera, that actually seems reasonable to me. The calls are supposed to be cached (per configured camera), so I do think there is something unexpected happening based on the log messages from the integration bug you created.

**Comment by felipecrs** [comment]
Right, but perhaps the card can somehow detect these duplicated cameras, check that they would end up with the same API call, and prevent making two of the same calls at the same time.

**Comment by dermotduffy** [comment]
> Right, but perhaps the card can somehow detect these duplicated cameras, check that they would end up with the same API call, and prevent making two of the same calls at the same time.

Yes, it could do that -- but should it? :-) The card makes a lot of API calls, on each one that's extra complexity for a corner case. If the substream functionality was implemented (as discussed in #934), this definitely doesn't feel worth it.

**Comment by felipecrs** [comment]
Oh yes, you are totally right. Supporting substreams directly would definitely solve the issue for me.

**Comment by dermotduffy** [comment]
@felipecrs Do a `pull` and try again, I think it'll be better. The recording calls will still be made, but (far) fewer of them -- hopefully this reduces the load on your Frigate backend, and thus the calls won't time out...

**Comment by felipecrs** [comment]
Wow, thank you, it's million times better now! Awesome!

**Comment by felipecrs** [comment]
BTW I noticed this in my HA logs... never had noticed it before:

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 01:59:03 (1 occurrences)
Last logged: 01:59:03

Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media without passing an entity_id")
```

Not sure if it's related...
